include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: npm-generic.yml
    # rules:
    #   - changes:
    #       - examples/browser/**/*

before_script:
  - cd examples/browser

variables:
  NODE_VERSION: 22
  OUTPUT_DIR: .output/public